import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'screens/dashboard_screen.dart';
import 'providers/dashboard_provider.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
import 'services/api_service.dart';
import 'firebase_options.dart'; // This will be generated by flutterfire configure

final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

Future<void> _showInsistentNotification(RemoteMessage message) async {
  print("Showing insistent alarm for: ${message.data}");
  final AndroidNotificationDetails androidPlatformChannelSpecifics =
      AndroidNotificationDetails(
    'alarm_clock_channel',
    'Alarm Clock Notifications',
    channelDescription: 'Loud, continuous ringing alarms for tasks',
    importance: Importance.max,
    priority: Priority.high,
    additionalFlags: Int32List.fromList(<int>[4]), // FLAG_INSISTENT = 4
  );
  final NotificationDetails platformChannelSpecifics =
      NotificationDetails(android: androidPlatformChannelSpecifics);
  
  await flutterLocalNotificationsPlugin.show(
    message.hashCode,
    message.data['title'] ?? 'Task Due!',
    message.data['body'] ?? 'You have a task due now.',
    platformChannelSpecifics,
  );
}

@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  print("Handling a background message: ${message.messageId}");
  await _showInsistentNotification(message);
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    const AndroidInitializationSettings initializationSettingsAndroid =
        AndroidInitializationSettings('@mipmap/ic_launcher');
    const InitializationSettings initializationSettings =
        InitializationSettings(android: initializationSettingsAndroid);
    await flutterLocalNotificationsPlugin.initialize(initializationSettings);

    const AndroidNotificationChannel channel = AndroidNotificationChannel(
      'alarm_clock_channel',
      'Alarm Clock Notifications',
      description: 'Loud, continuous ringing alarms for tasks',
      importance: Importance.max,
    );
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);

    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
    
    // Also trigger loud alarm when in foreground
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      _showInsistentNotification(message);
    });

    FirebaseMessaging messaging = FirebaseMessaging.instance;
    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
    
    if (settings.authorizationStatus == AuthorizationStatus.authorized) {
      String? token = await messaging.getToken();
      if (token != null) {
        print("FCM Token: $token");
        ApiService().registerToken(token);
      }
    }
  } catch (e) {
    print("Firebase init failed: $e");
  }

  runApp(const FlowMemApp());
}

class FlowMemApp extends StatelessWidget {
  const FlowMemApp({super.key});

  @override
  Widget build(BuildContext context) {
    // Vercel AMOLED Color Scheme
    const vercelBlack = Color(0xFF000000);
    const vercelGray = Color(0xFF1A1A1A);
    const vercelBorder = Color(0xFF2A2A2A);
    const vercelAccent = Color(0xFF0070F3);
    const vercelSuccess = Color(0xFF0DBC79);
    const vercelError = Color(0xFFE00);
    const vercelWarning = Color(0xFFF5A623);
    
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => DashboardProvider()),
      ],
      child: MaterialApp(
        title: 'FlowMem',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          brightness: Brightness.dark,
          scaffoldBackgroundColor: vercelBlack,
          primaryColor: vercelAccent,
          colorScheme: const ColorScheme.dark(
            background: vercelBlack,
            surface: vercelGray,
            primary: vercelAccent,
            secondary: vercelSuccess,
            error: vercelError,
            onBackground: Colors.white,
            onSurface: Colors.white,
          ),
          useMaterial3: true,
          fontFamily: 'Inter',
          textTheme: const TextTheme(
            displayLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.bold, color: Colors.white, letterSpacing: -1),
            displayMedium: TextStyle(fontSize: 24, fontWeight: FontWeight.bold, color: Colors.white, letterSpacing: -0.5),
            titleLarge: TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: Colors.white),
            titleMedium: TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: Colors.white),
            bodyLarge: TextStyle(fontSize: 16, color: Colors.white70),
            bodyMedium: TextStyle(fontSize: 14, color: Colors.white60),
            labelLarge: TextStyle(fontSize: 14, fontWeight: FontWeight.w600, color: Colors.white),
          ),
          cardTheme: CardThemeData(
            color: vercelGray,
            elevation: 0,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
              side: const BorderSide(color: vercelBorder, width: 1),
            ),
          ),
          appBarTheme: const AppBarTheme(
            backgroundColor: vercelBlack,
            elevation: 0,
            systemOverlayStyle: SystemUiOverlayStyle.light,
            iconTheme: IconThemeData(color: Colors.white),
          ),
          dividerTheme: const DividerThemeData(
            color: vercelBorder,
            thickness: 1,
          ),
        ),
        home: const DashboardScreen(),
      ),
    );
  }
}
